fix: typo for haskeys export
Qbox-project/qbx_core pull request #266
Opened 2023-11-24 19:29 UTC by dusan01

## Description

On a fresh install, you get "No such export HasKeys in resource qb-vehiclekeys" whenever you sit in the vehicle. I guess this was a typo in the last commit, so this fixes that problem.

## Checklist

- [x] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My code fits the style guidelines.
- [x] My PR fits the contribution guidelines.

2023-11-24 19:32 UTC, solareon requested changes

2023-11-24 19:32 UTC, solareon commented on config/client.lua
> +        return exports['qbx_vehiclekeys']:HasKeys()
```suggestion
        return exports.qbx_vehiclekeys:HasKeys()
```
Since there is no dash you can call it directly without the []

2023-11-24 19:53 UTC, Manason approved these changes

2023-11-25 17:34 UTC, MafewTM approved these changes

2023-11-25 17:35 UTC, merged