Update functions.lua
Qbox-project/qbx_core pull request #332
Opened 2024-01-25 19:30 UTC by SKITTLE6969

## Description

fix to GetClosestVehicle & GetClosestObject  if a null value is passed

## Checklist

- [ ] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [ ] My pull request fits the contribution guidelines & code conventions.

2024-01-25 22:42 UTC, MafewTM commented
Pretty sure these weren't added on purpose but we'll see

2024-01-25 23:28 UTC, D4isDAVID commented
> Pretty sure these weren't added on purpose but we'll see

Nope. I just forgot/didn't notice that these weren't added. We need this for backwards compatibility.

2024-01-25 23:30 UTC, D4isDAVID requested changes

2024-01-25 23:30 UTC, D4isDAVID commented on bridge/qb/client/functions.lua
> +    end
```suggestion
    coords = type(coords) == 'table' and vec3(coords.x, coords.y, coords.z) or coords or GetEntityCoords(cache.ped)
```
This part can be reduced.

2024-01-25 23:30 UTC, D4isDAVID commented on bridge/qb/client/functions.lua
> +    end
```suggestion
    coords = type(coords) == 'table' and vec3(coords.x, coords.y, coords.z) or coords or GetEntityCoords(cache.ped)
```
Same here.

2024-01-26 00:04 UTC, MafewTM approved these changes

2024-01-26 00:04 UTC, D4isDAVID approved these changes

2024-01-26 00:05 UTC, merged

2024-01-26 00:05 UTC, solareon approved these changes