fix(bridge/qb/client/functions): restore backwards compatibility
Qbox-project/qbx_core pull request #337
Opened 2024-01-28 23:46 UTC by Manason

v1.5.0 broke backwards compatibility by changing some function headers and behaviors. This restores the behavior to what it was prior to v1.5.0

2024-01-28 23:51 UTC, D4isDAVID commented
The original QBCore functions `GetVehicles`, `GetObjects`, `GetPlayers`, `GetClosestVehicle` and `GetClosestObject` don't actually take in an `ignoreList`. The original `GetClosestPlayer` doesn't take a `maxDistance` either.

Although it was like this before v1.5.0, is this not invalid? Or is this already used by some users?

2024-01-28 23:52 UTC, BerkieBb approved these changes

2024-01-29 00:03 UTC, D4isDAVID requested changes

2024-01-29 00:03 UTC, D4isDAVID commented on bridge/qb/client/functions.lua
> +    return #closeVeh == 0
Why can't we keep using `lib.getNearbyVehicles` here?

2024-01-29 00:03 UTC, D4isDAVID commented on bridge/qb/client/functions.lua
> +    return players
Suggestion: it is possible to refactor `getEntities` to accept a pool of entities or a list of players instead of a pool name to use it here too.

2024-01-29 00:41 UTC, D4isDAVID approved these changes

2024-01-29 16:36 UTC, merged