feat: event on group updates
Qbox-project/qbx_core pull request #415
Opened 2024-03-14 20:28 UTC by solareon

## Description

When updating groups for a player we don't trigger any event that can be consumed to update other resources. This adds a new event for resources to listen to and perform various functions such as updating UIs etc.

## Checklist

- [x] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My pull request fits the contribution guidelines & code conventions.

2024-03-14 20:34 UTC, FjamZoo commented
Wouldnt it be better just to send the name and the grade that was modified, and the name that was removed?

That way scripts can do individual checks like if x was removed do y

instead of having to iterate over the entire table

2024-03-14 20:54 UTC, FjamZoo requested changes

2024-03-14 20:54 UTC, FjamZoo commented on server/player.lua
> +        TriggerClientEvent('QBCore:Client:OnGangsUpdate', player.PlayerData.source, gangName, nil)
```suggestion
        TriggerEvent('QBCore:Server:OnGroupUpdate', player.PlayerData.source, gangName)
        TriggerClientEvent('QBCore:Client:OnGroupUpdate', player.PlayerData.source, gangName)
```

2024-03-14 20:54 UTC, FjamZoo commented on server/player.lua
> +        TriggerClientEvent('QBCore:Client:OnJobsUpdate', player.PlayerData.source, jobName, nil)
```suggestion
        TriggerEvent('QBCore:Server:OnGroupUpdate', player.PlayerData.source, jobName)
        TriggerClientEvent('QBCore:Client:OnGroupUpdate', player.PlayerData.source, jobName)
```

2024-03-14 20:54 UTC, FjamZoo commented on server/player.lua
> +        TriggerClientEvent('QBCore:Client:OnGangsUpdate', player.PlayerData.source, gangName, grade)
```suggestion
        TriggerEvent('QBCore:Server:OnGroupUpdate', player.PlayerData.source, gangName, grade)
        TriggerClientEvent('QBCore:Client:OnGroupUpdate', player.PlayerData.source, gangName, grade)
```

2024-03-14 20:54 UTC, FjamZoo commented on server/player.lua
> +        TriggerClientEvent('QBCore:Client:OnJobsUpdate', player.PlayerData.source, jobName, grade)
```suggestion
        TriggerEvent('QBCore:Server:OnGroupUpdate', player.PlayerData.source, jobName, grade)
        TriggerClientEvent('QBCore:Client:OnGroupUpdate', player.PlayerData.source, jobName, grade)
```

2024-03-14 20:57 UTC, FjamZoo approved these changes

2024-03-14 21:57 UTC, TonybynMp4 approved these changes

2024-03-15 02:16 UTC, Manason reviewed
Does this event already exist? If not shouldn't we name it qbx_core instead of QBCore?

2024-03-15 11:16 UTC, merged