refactor(character): Use tutorial natives instead of manual bucket setting
Qbox-project/qbx_core pull request #480
Opened 2024-06-05 21:04 UTC by solareon

## Description

Routing buckets may overlap. The natives do a better job of hiding the characters. This is similar to #473 but moves the tutorial end to the `QBCore:Client:OnPlayerLoaded` event to end the tutorial session with the appropriate native.

Additionally it only calls the tutorial session start one time if somehow the choosecharacter() function got called twice without being disabled cause who knows if that works right.

NOTE: I have **NOT** tested this. Do not merge without extensive testing in a multiplayer environment. 

## Checklist

- [ ] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My pull request fits the contribution guidelines & code conventions.

2024-10-04 07:12 UTC, Molicheu approved these changes

2024-10-04 08:18 UTC, Manason requested changes
Blocking on testing to be confirmed (in a multi-client environment)

2024-11-01 00:53 UTC, mafewtm commented
Tested by @D4isDAVID and appears to work as expected

2024-11-01 15:07 UTC, Manason approved these changes

2024-11-01 15:07 UTC, merged