fix(server/functions): exploitban yield until ids inserted
Qbox-project/qbx_core pull request #520
Opened 2024-07-19 10:55 UTC by solareon

## Description

Spawning off a thread for the ban insert while functionally correct the natives could fail to return the identifiers preventing the ban from being inserted. This moves the insert into a pcall which will yield until the ban is inserted.

## Checklist

- [ ] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My pull request fits the contribution guidelines & code conventions.

2024-07-19 14:00 UTC, Manason requested changes

2024-07-19 14:00 UTC, Manason commented on server/functions.lua
> +    if not success then lib.print.error(errorResult) end
Shouldn't it return here to prevent incorrectly logging that someone was banned and also if we fail to ban, maybe we want to fail the kick as well?

2024-07-19 14:03 UTC, solareon commented on server/functions.lua
> +    if not success then lib.print.error(errorResult) end
Well prior to this the ban would fail inserting anyway due to the natives returning nothing since the source was gone by the time we polled for licenses. I can see the benefit of returning after the kick and not logging since it didn't succeed

2024-08-05 07:20 UTC, solareon commented on server/functions.lua
> +    if not success then lib.print.error(errorResult) end
Refactored this with a better log message.

2024-08-05 08:26 UTC, Manason approved these changes

2024-08-05 20:26 UTC, FjamZoo approved these changes

2024-08-05 20:26 UTC, merged