feat(server/events): statebag handler for hunger/stress/thirst
Qbox-project/qbx_core pull request #540
Opened 2024-08-17 22:06 UTC by solareon

## Description

Setting the statebags outside of the core never actually updates the metadata values which other resources may depend on. This corrects that with a guard check to prevent infinite recursion.

## Checklist

- [ ] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My pull request fits the contribution guidelines & code conventions.

2024-08-17 22:23 UTC, Manason approved these changes
Should this PR also include a guard clause to prevent the statebag from being set twice? https://github.com/Qbox-project/qbx_core/blob/main/server/player.lua#L670 Small optimization as it would still terminate after goes around one time.

2024-08-18 20:28 UTC, mafewtm approved these changes

2024-08-19 13:29 UTC, Manason requested changes
Tested and it results in infinite loop leading to stack overflow.

2024-08-20 13:47 UTC, KostaZx approved these changes

2024-08-20 15:14 UTC, mafewtm approved these changes
Tested and appears to work as intended

2024-08-20 15:37 UTC, Manason approved these changes

2024-08-20 15:42 UTC, merged